routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ImageOperationsController;
use App\Http\Controllers\Admin\AdminPanelController;
use App\Http\Controllers\Admin\Users\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [ImageOperationsController::class, 'index'])->name('service.index');
Route::prefix('service')->as('service.')->group(function (){
    Route::post('/store', [ImageOperationsController::class, 'store'])->name('store');
});
Route::get('/zip', [ImageOperationsController::class, 'zip'])->name('zip');

Route::middleware(['admin', 'auth'])->namespace('Admin')->prefix('admin')->as('admin.')->group(function (){
    Route::get('/', [AdminPanelController::class, 'index'])->name('index');
});
Route::middleware(['admin', 'auth'])->as('users.')->group(function(){
    Route::resource('/user', UserController::class)->except([
        'show'
    ]);
});

resources/views/service/forgetPassword.blade.php
@extends('layouts.main')
@section('title')
    Забыли пароль?
@endsection
@section('content')
    <section class="forget">
        <div class="forget__container container">
            <h1 class="forget__title">Забыли пароль?</h1>
            <form class="forget__form" action="{{route('forget.store')}}" method="post">
                @csrf
                <label for="email" class="forget__label">
                    <span class="forget__text">Введите email: </span>
                    <input type="email" class="forget__input" name="email"  placeholder="Email" value="{{old('email')}}">
                    @error('email')
                    <span class="error">{{$message}}</span>
                    @enderror
                </label>
                <button class="forget__button" type="submit">Отправить</button>
            </form>
        </div>
    </section>
@endsection

resources/views/service/index.blade.php
@extends('layouts.main')
@section('title')
    Главная
@endsection
@section('content')
    <section class="hero">
        <div class="container hero__container">
            <h1 class="hero__title">Онлайн конвертер <span>изображений</span></h1>
            <form class="hero__form" action="{{route('service.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <label class="hero__label" for="image">
                    <span class="hero__text">Добавьте изображение</span>
                    <input class="hero__input" type='file' multiple name="image[]" id="image">
                    <span class="choose">Выберите файл</span>
                    @error('image')
                    <span class="error">{{$message}}</span>
                    @enderror
                </label>
                <label class="hero__label" for="width">
                    <span class="hero__text">Введите ширину изображения</span>
                    <input class="hero__input value="{{old('width')}}" type="text" name="width" placeholder="Ширина">
                    @error('width')
                    <span class="error">{{$message}}</span>
                    @enderror
                </label>
                <label class="hero__label" for="width">
                    <span class="hero__text">Введите высоту изображения</span>
                    <input class="hero__input value="{{old('height')}}" type="text" name="height" placeholder="Высота">
                    @error('height')
                    <span class="error">{{$message}}</span>
                    @enderror
                </label>
                <label class="hero__label" for="extension">
                    <span class="hero__text">Введите формат изображения</span>
                    <select class="hero__select" name="extension">
                        <option value="0" disabled selected>Выберите изображение</option>
                        <option value="jpg">jpg</option>
                        <option value="png">png</option>
                        <option value="jpeg">jpeg</option>
                    </select>
                </label>
                <button class="hero__button" type="submit">Отправить</button>
            </form>
        </div>
    </section>
@endsection

resources/views/service/login.blade.php
@extends('layouts.main')
@section('title')
    Авторизация
@endsection
@section('content')
<section class="auth">
    <div class="auth__container container">
        <h1 class="auth__title">Вход в аккаунт</h1>
        <form class="auth__form" action="{{route('login.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <label for="email" class="auth__label">
                <span class="auth__text">Введите email: </span>
                <input type="email" class="auth__input" name="email"  placeholder="Email" value="{{old('email')}}">
                @error('email')
                <span class="error">{{$message}}</span>
                @enderror
            </label>
            <label for="password" class="auth__label">
                <span class="auth__text">Введите пароль: </span>
                <input type="password" class="auth__input" name="password" placeholder="Пароль" value="{{old('password')}}">
                @error('password')
                <span class="error">{{$message}}</span>
                @enderror
            </label>
            <button type="submit">Отправить</button>
            <label for="remember" class="auth__label" id="remember_label">
                <input type="checkbox" name="remember" id="remember">
                <span class="auth__text">Запонмить меня</span>
                <form action="{{route('forget.index')}}">
                    @csrf
                    <a href="{{route('forget.index')}}">Забыли пароль</a>
                </form>
            </label>

        </form>
    </div>
</section>
@endsection

resources/views/service/register.blade.php
@extends('layouts.main')
@section('title')
    Регистрация
@endsection
@section('content')
    <section class="register">
        <div class="register__container container">
            <h1 class="register__title">Форма регистрации</h1>
            <form class="register__form" action="{{route("register.store")}}" method="post">
                @csrf
                <label for="name" class="register__label">
                    <span class="register__text">Введите имя: </span>
                    <input value="{{old('name')}}" type="text" class="register__input" name="name" placeholder="Имя">
                    @error('name')
                    <span class="error">{{$message}}</span>
                    @enderror
                </label>

                <label for="email" class="register__label">
                    <span class="register__text">Введите email: </span>
                    <input value="{{old('email')}}" type="email" class="register__input" name="email"  placeholder="Email">
                    @error('email')
                    <span class="error">{{$message}}</span>
                    @enderror
                </label>

                <label for="password" class="register__label">
                    <span class="register__text">Введите пароль: </span>
                    <input value="{{old('password')}}" type="password" class="register__input" name="password" placeholder="Пароль">
                    @error('password')
                    <span class="error">{{$message}}</span>
                    @enderror
                </label>
                <label for="password_confirmation" class="register__label">
                    <span class="register__text">Подтвердите пароль: </span>
                    <input value="{{old('password_confirmation')}}" type="password" class="register__input" name="password_confirmation" placeholder="Повторите пароль">
                </label>
                <button class="register__button" type="submit">Отправить</button>
            </form>
        </div>
    </section>
@endsection

resources/views/service/reset-password.blade.php
@extends('layouts.main')
@section('title')
    Сброс пароля
@endsection
@section('content')
    <section class="reset_pass">
        <div class="reset_pass__container">
            <h1 class="reset_pass__title">
                Сброс пароля
            </h1>
            <form action="{{route('password.update')}}" method="post">
                @csrf
                <input type="hidden" value="{{$request->token}}" name="token">
                <span>Email</span><br>
                <input type="text" name="email"><br>
                <span>Пароль</span><br>
                <input type="text" name="password"><br>
                <span>Пароль</span><br>
                <input type="text" name="password_confirmation"><br>
                <button>Отправить</button>
            </form>
        </div>
    </section>
@endsection