routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ImageOperationsController;
use App\Http\Controllers\Admin\AdminPanelController;
use App\Http\Controllers\Admin\Users\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [ImageOperationsController::class, 'index'])->name('service.index');
Route::prefix('service')->as('service.')->group(function (){
    Route::post('/store', [ImageOperationsController::class, 'store'])->name('store');
});
Route::get('/zip', [ImageOperationsController::class, 'zip'])->name('zip');

Route::middleware(['admin', 'auth'])->namespace('Admin')->prefix('admin')->as('admin.')->group(function (){
    Route::get('/', [AdminPanelController::class, 'index'])->name('index');
});
Route::middleware(['admin', 'auth'])->as('users.')->group(function(){
    Route::resource('/user', UserController::class)->except([
        'show'
    ]);
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'id',
        'name',
        'email',
        'password',
    ];

    public function images(){
        return $this->hasMany(Image::class);
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/Users/UserController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\AddUserRequest;
use App\Http\Requests\UpdateUserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::query()->orderBy('created_at', 'asc')->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function show(){
        return 'BEBRA';
    }


    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddUserRequest $request)
    {
        User::query()->create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);
        return redirect()->back()->with('adminStatus', 'Пользователь успешно добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $user->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);
        return redirect()->back()->with('admin_status', 'Пользователь обновлён');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->back()->with('admin_status', 'Пользователь удалён');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.main')

@section('content')
<form method="POST" action="{{route('users.user.store')}}">
    @csrf
    <div class="card-body">
        <div class="form-group">
            <label for="exampleInputEmail1">Имя</label>
            <input name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
            @error('name')
                <span class="red">{{$message}}</span>
            @enderror
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
            @error('email')
                <span class="red">{{$message}}</span>
            @enderror
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            @error('password')
                <span class="red">{{$message}}</span>
            @enderror
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Добавить</button>
    </div>
</form>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <form method="POST" action="{{route('users.user.update', $user->id)}}">
        @csrf
        @method('PATCH')
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Имя</label>
                <input name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter email" value="{{$user->name}}">
                @error('name')
                <span class="red">{{$message}}</span>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" value="{{$user->email}}">
                @error('email')
                <span class="red">{{$message}}</span>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" value="{{$user->password}}">
                @error('password')
                  <span class="red">{{$message}}</span>
                @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
    </form>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <table class="table pt-5">
        <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Email</th>
            <th scope="col">Редактировать</th>
            <th scope="col">Добавить</th>
            <th scope="col">Удалить</th>
            <th scope="col">Тип пользователя</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>
                <form action="{{route('users.user.edit', $user->id)}}" method="GET">
                    @csrf
                    <button type="submit" class="btn btn-block btn-primary btn-sm">Редактировать</button>
                </form>
            </td>
            <td>
                <form action="{{route('users.user.create')}}" method="GET">
                    @csrf
                    <button type="submit" class="btn btn-block btn-success btn-sm">Добавить</button>
                </form>
            </td>

            <td>
                <form action="{{route('users.user.destroy', $user->id)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-block btn-danger btn-sm">Удалить</button>
                </form>
            </td>
            <td>
                <li>{{\App\Enums\RoleEnum::from($user->role)->label()}}</li>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table
@endsection